#!/bin/bash
clear
url=$1
echo "----All-in-one Download Script for Termux----"
echo "----------Last updated Nov 06 2022----------"
echo "--------------------------------------------"
echo "1: Download with yt-dlp (Fixed Bandwidth Throttling by YouTube)"
echo "2: Download with ffmpeg(m3u8/m3u)"
echo "3: Download with wget (Recursive)"
echo "4: Download with spotdl (Spotify All-in-one)"
echo "5: Download with yt-dlp and extract audio (Fixed Bandwidth Throttling by YouTube)"
echo "6: Download with youtube-dl"
echo "7: Download with youtube-dl and extract audio"
echo "8: Download with you-get"
echo "Default: Download with yt-dlp (Fixed Bandwidth Throttling by YouTube)"
read n

if [ "$n" == '2' ]; then
echo "Output Filename:"
read name
ffmpeg -i "$url" -c copy -bsf:a aac_adtstoasc "/data/data/com.termux/files/home/storage/downloads/$name"
else

if [ "$n" == '3' ]; then
wget -P "/data/data/com.termux/files/home/storage/downloads/" -c --mirror  --recursive --no-clobber  --page-requisites --html-extension --convert-links -e robots=off --restrict-file-names=windows --no-parent "$url"
else


if [ "$n" == '4' ]; then 
[ ! -d "/data/data/com.termux/files/home/storage/shared/spotdl" ] && mkdir "/data/data/com.termux/files/home/storage/shared/spotdl"
[[ $url == *"track"* ]] && spotdl download --output "/data/data/com.termux/files/home/storage/shared/spotdl/{artist}-{title}" --bitrate 320k "$url"
[[ $url == *"playlist"* ]] && spotdl download --output "/data/data/com.termux/files/home/storage/shared/spotdl/{artist}-{title}" --bitrate 320k "$url"
[[ $url == *"album"* ]] && spotdl download --output "/data/data/com.termux/files/home/storage/shared/spotdl/{title}" --bitrate 320k "$url"
[[ $url == *"artist"* ]] && spotdl download --output "/data/data/com.termux/files/home/storage/shared/spotdl/{artist}/{title}" --bitrate 320k "$url"
else

if [ "$n" == '5' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/shared/youtube-dl" ] && mkdir "/data/data/com.termux/files/home/storage/shared/youtube-dl"
yt-dlp --extractor-args "youtube:player_client=android" -x --audio-format mp3 -f bestaudio --audio-quality 0 --add-metadata --embed-thumbnail -c -i "$url" -o "/data/data/com.termux/files/home/storage/shared/youtube-dl/%(title)s.%(ext)s"
else

if [ "$n" == '6' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/shared/youtube-dl" ] && mkdir "/data/data/com.termux/files/home/storage/shared/youtube-dl"
youtube-dl -c -i "$url" -o "/data/data/com.termux/files/home/storage/shared/youtube-dl/%(title)s.%(ext)s"
else

if [ "$n" == '7' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/shared/youtube-dl" ] && mkdir "/data/data/com.termux/files/home/storage/shared/youtube-dl"
youtube-dl -x --audio-format mp3 -f bestaudio --audio-quality 0 -c -i "$url" -o "/data/data/com.termux/files/home/storage/shared/youtube-dl/%(title)s.%(ext)s"
else

if [ "$n" == '8' ]; then
[ ! -d "/data/data/com.termux/files/home/storage/downloads/you-get" ] && mkdir "/data/data/com.termux/files/home/storage/downloads/you-get"
you-get -o "/data/data/com.termux/files/home/storage/downloads/you-get" "$url"
else

[ ! -d "/data/data/com.termux/files/home/storage/shared/youtube-dl" ] && mkdir "/data/data/com.termux/files/home/storage/shared/youtube-dl"
yt-dlp  --extractor-args "youtube:player_client=android" -c -i "$url" -o "/data/data/com.termux/files/home/storage/shared/youtube-dl/%(title)s.%(ext)s"
fi
fi
fi
fi
fi
fi
fi


